# Generated by Django 6.0.3 on 2026-03-18 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('enemy_type', models.CharField(choices=[('normal', 'Normal'), ('elite', 'Elite'), ('boss', 'Boss')], default='normal', max_length=20)),
                ('base_level', models.IntegerField(default=1)),
                ('icon', models.CharField(default='👹', max_length=10)),
                ('base_hp', models.IntegerField(default=50)),
                ('base_attack', models.IntegerField(default=8)),
                ('base_defense', models.IntegerField(default=2)),
                ('xp_reward', models.IntegerField(default=20)),
                ('gold_reward', models.IntegerField(default=10)),
                ('loot_chance', models.FloatField(default=0.3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('potion', 'Potion'), ('chest', 'Chest')], default='weapon', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('icon', models.CharField(default='🗡️', max_length=10)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('hp_restore', models.IntegerField(default=0)),
                ('level_required', models.IntegerField(default=1)),
                ('gold_value', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chest_type', models.CharField(choices=[('wooden', 'Wooden Chest'), ('silver', 'Silver Chest'), ('golden', 'Golden Chest'), ('legendary', 'Legendary Chest')], default='wooden', max_length=20)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('gold_min', models.IntegerField(default=10)),
                ('gold_max', models.IntegerField(default=50)),
                ('guaranteed_items', models.IntegerField(default=1)),
                ('bonus_item_chance', models.FloatField(default=0.3)),
                ('level_required', models.IntegerField(default=1)),
                ('possible_items', models.ManyToManyField(blank=True, related_name='chest_sources', to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('stat_points', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=5)),
                ('dexterity', models.IntegerField(default=5)),
                ('intelligence', models.IntegerField(default=5)),
                ('vitality', models.IntegerField(default=5)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('gold', models.IntegerField(default=50)),
                ('enemies_defeated', models.IntegerField(default=0)),
                ('total_damage_dealt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=100)),
                ('enemy_level', models.IntegerField(default=1)),
                ('player_level', models.IntegerField(default=1)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('flee', 'Flee')], max_length=20)),
                ('xp_gained', models.IntegerField(default=0)),
                ('gold_gained', models.IntegerField(default=0)),
                ('turns', models.IntegerField(default=0)),
                ('log_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_dropped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_logs', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skill_type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('utility', 'Utility')], default='attack', max_length=20)),
                ('tier', models.IntegerField(default=1)),
                ('level_required', models.IntegerField(default=1)),
                ('stat_points_cost', models.IntegerField(default=1)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('crit_chance_bonus', models.FloatField(default=0.0)),
                ('icon', models.CharField(default='⚔️', max_length=50)),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='game.skill')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='players', to='game.skill'),
        ),
        migrations.CreateModel(
            name='PlayerChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chest')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'chest')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
    ]
