# Generated by Django 6.0.3 on 2026-03-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.FloatField(default=0.0)),
                ('density', models.FloatField(default=0.0)),
                ('material_grade', models.IntegerField(default=0)),
                ('temper_count', models.IntegerField(default=0)),
                ('ember_dust', models.FloatField(default=0.0)),
                ('total_strikes', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forge_state', to='game.player')),
            ],
        ),
    ]
