# Generated by Django 6.0.3 on 2026-03-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_forgestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgestate',
            name='blade_attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forgestate',
            name='blade_defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('potion', 'Potion'), ('chest', 'Chest'), ('material', 'Material')], default='weapon', max_length=20),
        ),
        migrations.CreateModel(
            name='EncounteredEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_fought', models.IntegerField(default=0)),
                ('times_won', models.IntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encountered_enemies', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'enemy')},
            },
        ),
    ]
