# Generated by Django 6.0.3 on 2026-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_encounteredenemy_blade_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatlog',
            name='variant',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
